---
- hosts: "{{ HOSTS }}"
  become: true
  become_user: root
  vars_files: checkout_vars.yml
  tasks:
    - name: Copy lisp.config
      copy: 
        src: "{{ REPO_PATH }}/lisp.config"
        dest: /home/ubuntu/lisp-config
        remote_src: yes

    - name: copy config lispers.net
      community.docker.docker_container_exec:
        container: "{{ ROLE_LISP }}"
        argv:
          - /bin/tcsh
          - "-c"
          - "cp -rf /lisp-config/lisp.config /lispers.net"
        chdir: /lispers.net
    
    - name: restart lispers.net
      community.docker.docker_container_exec:
        container: "{{ ROLE_LISP }}"
        argv:
          - /bin/tcsh
          - "-c"
          - "./RL"
        chdir: /lispers.net
      register: result

    - name: Print stderr lines
      debug:
        var: result.stdout